const PHONE_PREFIX_MAP: { prefix: string; country: string }[] = [
  { prefix: "+353", country: "Ireland" },
  { prefix: "+351", country: "Portugal" },
  { prefix: "+358", country: "Finland" },
  { prefix: "+356", country: "Malta" },
  { prefix: "+372", country: "Estonia" },
  { prefix: "+371", country: "Latvia" },
  { prefix: "+370", country: "Lithuania" },
  { prefix: "+385", country: "Croatia" },
  { prefix: "+381", country: "Serbia" },
  { prefix: "+386", country: "Slovenia" },
  { prefix: "+420", country: "Czech Republic" },
  { prefix: "+421", country: "Slovakia" },
  { prefix: "+36", country: "Hungary" },
  { prefix: "+90", country: "Türkiye" },
  { prefix: "+44", country: "United Kingdom" },
  { prefix: "+49", country: "Germany" },
  { prefix: "+48", country: "Poland" },
  { prefix: "+33", country: "France" },
  { prefix: "+31", country: "Netherlands" },
  { prefix: "+32", country: "Belgium" },
  { prefix: "+43", country: "Austria" },
  { prefix: "+41", country: "Switzerland" },
  { prefix: "+47", country: "Norway" },
  { prefix: "+46", country: "Sweden" },
  { prefix: "+45", country: "Denmark" },
  { prefix: "+39", country: "Italy" },
  { prefix: "+34", country: "Spain" },
  { prefix: "+30", country: "Greece" },
  { prefix: "+40", country: "Romania" },
  { prefix: "+359", country: "Bulgaria" },
  { prefix: "+380", country: "Ukraine" },
  { prefix: "+77", country: "Kazakhstan" },
  { prefix: "+7", country: "Russia" },
  { prefix: "+993", country: "Turkmenistan" },
  { prefix: "+996", country: "Kyrgyzstan" },
  { prefix: "+998", country: "Uzbekistan" },
  { prefix: "+98", country: "Iran" },
  { prefix: "+966", country: "Saudi Arabia" },
  { prefix: "+971", country: "UAE" },
  { prefix: "+974", country: "Qatar" },
  { prefix: "+965", country: "Kuwait" },
  { prefix: "+973", country: "Bahrain" },
  { prefix: "+968", country: "Oman" },
  { prefix: "+964", country: "Iraq" },
  { prefix: "+962", country: "Jordan" },
  { prefix: "+961", country: "Lebanon" },
  { prefix: "+963", country: "Syria" },
  { prefix: "+20", country: "Egypt" },
  { prefix: "+212", country: "Morocco" },
  { prefix: "+213", country: "Algeria" },
  { prefix: "+216", country: "Tunisia" },
  { prefix: "+218", country: "Libya" },
  { prefix: "+249", country: "Sudan" },
  { prefix: "+92", country: "Pakistan" },
  { prefix: "+91", country: "India" },
  { prefix: "+880", country: "Bangladesh" },
  { prefix: "+94", country: "Sri Lanka" },
  { prefix: "+977", country: "Nepal" },
  { prefix: "+61", country: "Australia" },
  { prefix: "+64", country: "New Zealand" },
  { prefix: "+1", country: "USA" },
  { prefix: "+52", country: "Mexico" },
  { prefix: "+55", country: "Brazil" },
  { prefix: "+54", country: "Argentina" },
  { prefix: "+56", country: "Chile" },
  { prefix: "+57", country: "Colombia" },
];

export function detectCountryFromPhone(phone: string): string | null {
  if (!phone || !phone.startsWith("+")) return null;
  const sorted = [...PHONE_PREFIX_MAP].sort((a, b) => b.prefix.length - a.prefix.length);
  const match = sorted.find((p) => phone.startsWith(p.prefix));
  return match ? match.country : null;
}
